language: java
jdk:
    - oraclejdk8

after_success:
- ./gradlew test jacocoTestReport coveralls

notifications:
  email:
    recipients:
      - wuyichen24@gmail.com
    on_success: never
    on_failure: always

services:
  - mysql

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('6ytow2-;S3lA') WHERE user='root';\n"
  - mysql -u root --password="6ytow2-;S3lA" < config/travis.sql
